CREATE TRIGGER TG_CLIENTES_IDADE ON CLIENTES
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
SELECT CPF, IDADE, DATA_NASCIMENTO, 
    DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) 
FROM CLIENTES
END;

INSERT INTO CLIENTES (
CPF, NOME, ENDERECO,
BAIRRO, CIDADE, ESTADO,
CEP, DATA_NASCIMENTO, IDADE,
GENERO, LIMITE_CREDITO, VOLUME_COMPRA,
PRIMEIRA_COMPRA
)
VALUES ('1183592810', 'Pessoa', 'R. Rua', 'Bairro', 'São Paulo', 
        'SP', '48251038', '20085403', 30, 'F', 170000, 25400,0);

SELECT DATA_NASCIMENTO, IDADE WHERE CPF = '1183592810';