INSERT INTO CLIENTES SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO,
CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, GENERO, 
LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA,
PRIMEIRA_COMPRA FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES
WHERE CPF <> '1471156710' AND  CPF <> '19290992743' AND  CPF <> '2600586709';
